# exit-code: 1
scan:
  scanners:
    - secret
    - misconfig
misconfiguration:
  scanners:
    - terraform
output: trivy-results.sarif
format: sarif
ignore-unfixed: true
severity:
  - UNKNOWN
  - MEDIUM
  - HIGH
  - CRITICAL
